apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
  labels:
    app: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website-container
        image: premgowda07/static-website:v1  # Your Docker image
        ports:
        - containerPort: 80  # Exposing port 80 inside the container
        env:
        - name: ENV_VARIABLE  # Optional: Add any environment variables here
          value: "your-value"
